version: "3.8"

services:
  myss1:
    image: niis/xroad-security-server:jammy-7.4.0
    container_name: myss1
    ports:
      - "8081:8080"
      - "8444:8443"
      - "4003:4000"
      - "5500:5500"
      - "5577:5577"
    volumes:
      - ./myss1/etc-xroad:/etc/xroad
      - ./myss1/var-lib-xroad:/var/lib/xroad
      - ./myss1/var-lib-postgresql:/var/lib/postgresql
      - ./myss1/tmp:/tmp
    networks:
      - xroad-network

  myss2:
    image: niis/xroad-security-server:jammy-7.4.0
    container_name: myss2
    ports:
      - "8082:8080"
      - "8445:8443"
      - "4005:4000"
      - "5501:5500"
      - "5578:5577"
    volumes:
      - ./myss2/etc-xroad:/etc/xroad
      - ./myss2/var-lib-xroad:/var/lib/xroad
      - ./myss2/var-lib-postgresql:/var/lib/postgresql
      - ./myss2/tmp:/tmp
    networks:
      - xroad-network

  cserver:
    image: niis/xroad-central-server:jammy-7.4.2
    container_name: cserver
    ports:
      - "80:80"
      - "4000:4000"
      - "4001:4001"
      - "4002:4002"
      - "8888:8888"
      - "8899:8899"
    volumes:
      - ./cserver/etc-xroad:/etc/xroad
      - ./cserver/var-lib-xroad:/var/lib/xroad
      - ./cserver/home:/home
      - ./cserver/usr-lib-nginx:/var/lib/nginx
      - ./cserver/tmp:/tmp
    networks:
      - xroad-network

networks:
  xroad-network: